Calculate minimum distance between two GeoFeatures
NetLogo/GIS-Extension pull request #46
Opened 2022-12-12 12:08 UTC by EwoutH

Adds a `minimum-distance-of` function to the NetLogo GIS Extension.

This combines #17, #18 and #19, originally written by @josephzhao.

2022-12-12 16:32 UTC, LaCuneta requested changes
Hey, thanks for pulling this together.  Unfortunately when I went to compile it I found a bunch of syntax errors in the code.  As such I suspect this may not actually work as I don't think the author could've actually tested it, but I may be wrong.  I left comments on the code issues.

Other things I'd want to see before merging:

- Add at least one, and maybe more, language tests for this functionality.  You can [read about language tests in the NetLogo wiki](https://github.com/NetLogo/NetLogo/wiki/Language-tests), and there are [a lot of examples already in the GIS test file](https://github.com/NetLogo/GIS-Extension/blob/hexy/tests.txt).  You can run the tests with `sbt test`
- We'd need the prim added to the documentation.  The short version is to [edit `documentation.conf`](https://github.com/NetLogo/GIS-Extension/blob/hexy/documentation.conf) then run `sbt extensionDocument` to generate the `README.md` and commit both files.  You can check out [the `netlogo-extension-documentation` plugin for more info](https://github.com/NetLogo/netlogo-extension-documentation).

If you get things working just let me know and I'll be happy to re-test and merge.

2022-12-12 16:32 UTC, LaCuneta commented on src/org/myworldgis/netlogo/VectorDataset.java
> +                    for (Iterator<VectorFeature> i = dataset.getFeatures().iterator(); i.hasNext();) {
Need to add an import for `java.util.Iterator` at the top of the file.

2022-12-12 16:32 UTC, LaCuneta commented on src/org/myworldgis/netlogo/VectorFeature.java
> +    public double getDistance (Geometry geometry) {
Need to return a `Double` here as it can be `null` and so the value type of `double` won't work.

2022-12-12 16:32 UTC, LaCuneta commented on src/org/myworldgis/netlogo/VectorFeature.java
> +        if( _geometry ===null|| geometry === null ||geometry.isEmpty()) {
Java uses `==` to check equality, not `===`.  Also the spacing needs to be fixed with spaces around the `||` operators.  We also prefer a space after the keyword and before the open paren, so `if (_geometry...`

2022-12-14 17:41 UTC, EwoutH commented
Thanks a lot for the quick and extensive reply. I fixed the cases you mentioned in the review in 34a1ecb.

Unfortunately, I'm not a Java dev (and to be honest, not thinking of becoming one), so further development and testing is difficult for me. So this is probably as far as I can get this PR. Maybe @josephzhao is still interested in finishing what he started, or you or someone else want to finish it.

I've checked the "Allow edits by maintainers" checkbox on this PR. I also think you can go to https://github.dev/NetLogo/GIS-Extension/pull/46 (notice the .dev) and add commits to this PR. And otherwise, (anyone) feel fully free to take the [patch of this PR](https://patch-diff.githubusercontent.com/raw/NetLogo/GIS-Extension/pull/46.patch) and build on from there.

2025-11-11 19:10 UTC, closed without merging

2025-11-11 20:43 UTC, EwoutH commented
Probably good to close this PR as it is stale indeed.

However, I still think this feature is useful, so I wrote it up in https://github.com/NetLogo/GIS-Extension/issues/52.